-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.countries (
  id bigint NOT NULL DEFAULT nextval('countries_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  alpha2 text,
  slug text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT countries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tournaments (
  id bigint NOT NULL DEFAULT nextval('tournaments_id_seq'::regclass),
  external_id bigint NOT NULL UNIQUE,
  name text NOT NULL,
  slug text,
  country_id bigint,
  category text,
  created_at timestamp with time zone DEFAULT now(),
  logo_storage_path text,
  CONSTRAINT tournaments_pkey PRIMARY KEY (id),
  CONSTRAINT tournaments_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id)
);
CREATE TABLE public.seasons (
  id bigint NOT NULL DEFAULT nextval('seasons_id_seq'::regclass),
  external_id bigint NOT NULL UNIQUE,
  name text,
  year text,
  tournament_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT seasons_pkey PRIMARY KEY (id),
  CONSTRAINT seasons_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.teams (
  id bigint NOT NULL DEFAULT nextval('teams_id_seq'::regclass),
  external_id bigint NOT NULL UNIQUE,
  name text NOT NULL,
  short_name text,
  country text,
  slug text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  stadium_id bigint,
  crest_storage_path text,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_stadium FOREIGN KEY (stadium_id) REFERENCES public.stadiums(id)
);
CREATE TABLE public.players (
  id bigint NOT NULL DEFAULT nextval('players_id_seq'::regclass),
  external_id bigint NOT NULL UNIQUE,
  name text NOT NULL,
  position text,
  nationality text,
  date_of_birth date,
  market_value bigint,
  team_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  preferred_foot text,
  contract_until date,
  height_cm integer,
  jersey_number integer,
  position_detailed text,
  current_injury boolean DEFAULT false,
  injury_status text,
  injury_reason text,
  injury_return_days integer,
  primary_position text,
  secondary_position text,
  tertiary_position text,
  nationality_code text,
  injury_expected_return_days integer,
  injury_end_timestamp bigint,
  injury_start_timestamp bigint,
  injury_updated_timestamp bigint,
  injury_severity_score numeric,
  short_name text,
  CONSTRAINT players_pkey PRIMARY KEY (id),
  CONSTRAINT players_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.matches (
  id bigint NOT NULL DEFAULT nextval('matches_id_seq'::regclass),
  external_match_id bigint NOT NULL UNIQUE,
  home_team_id bigint NOT NULL,
  away_team_id bigint NOT NULL,
  date timestamp with time zone NOT NULL,
  competition text,
  season text,
  status text NOT NULL DEFAULT 'scheduled'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  venue_id bigint,
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id),
  CONSTRAINT matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id),
  CONSTRAINT fk_match_venue FOREIGN KEY (venue_id) REFERENCES public.stadiums(id)
);
CREATE TABLE public.match_results (
  id bigint NOT NULL DEFAULT nextval('match_results_id_seq'::regclass),
  match_id bigint NOT NULL UNIQUE,
  home_score integer,
  away_score integer,
  half_time_home_score integer,
  half_time_away_score integer,
  winner_team_id bigint,
  status text NOT NULL DEFAULT 'scheduled'::text,
  updated_at timestamp with time zone DEFAULT now(),
  match_date timestamp with time zone,
  CONSTRAINT match_results_pkey PRIMARY KEY (id),
  CONSTRAINT match_results_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_results_winner_team_id_fkey FOREIGN KEY (winner_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_squads_snapshot (
  id bigint NOT NULL DEFAULT nextval('team_squads_snapshot_id_seq'::regclass),
  team_id bigint NOT NULL,
  snapshot_date date NOT NULL,
  players_count integer,
  avg_age numeric,
  foreign_players_count integer,
  domestic_players_count integer,
  created_at timestamp with time zone DEFAULT now(),
  average_market_value bigint,
  injured_player_count integer DEFAULT 0,
  foreign_player_pct numeric,
  injured_player_pct numeric,
  CONSTRAINT team_squads_snapshot_pkey PRIMARY KEY (id),
  CONSTRAINT team_squads_snapshot_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.player_transfers (
  id bigint NOT NULL DEFAULT nextval('player_transfers_id_seq'::regclass),
  player_id bigint NOT NULL,
  from_team_id bigint,
  to_team_id bigint,
  transfer_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  transfer_fee bigint,
  transfer_fee_currency text,
  transfer_type integer,
  source text DEFAULT 'squad_diff'::text,
  CONSTRAINT player_transfers_pkey PRIMARY KEY (id),
  CONSTRAINT player_transfers_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT player_transfers_from_team_id_fkey FOREIGN KEY (from_team_id) REFERENCES public.teams(id),
  CONSTRAINT player_transfers_to_team_id_fkey FOREIGN KEY (to_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_form_history (
  id bigint NOT NULL DEFAULT nextval('team_form_history_id_seq'::regclass),
  team_id bigint NOT NULL,
  match_id bigint NOT NULL,
  result character NOT NULL,
  goals_for integer,
  goals_against integer,
  points integer,
  created_at timestamp with time zone DEFAULT now(),
  match_date timestamp with time zone,
  is_home boolean,
  half_time_score_for integer,
  half_time_score_against integer,
  btts boolean,
  CONSTRAINT team_form_history_pkey PRIMARY KEY (id),
  CONSTRAINT team_form_history_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_form_history_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.team_intelligence (
  id bigint NOT NULL DEFAULT nextval('team_intelligence_id_seq'::regclass),
  team_id bigint NOT NULL UNIQUE,
  readiness_score numeric,
  fatigue_index numeric,
  rotation_pressure_index numeric,
  form_index numeric,
  last_5_points integer,
  last_10_points integer,
  congestion_score numeric,
  rest_days_avg numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  travel_fatigue_score numeric,
  travel_load_km numeric,
  active_competitions integer DEFAULT 0,
  squad_stability_score numeric,
  injury_burden_score numeric,
  squad_depth_score numeric,
  injured_market_value bigint DEFAULT 0,
  available_market_value bigint DEFAULT 0,
  lineup_versatility_score numeric,
  CONSTRAINT team_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT team_intelligence_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.player_intelligence (
  id bigint NOT NULL DEFAULT nextval('player_intelligence_id_seq'::regclass),
  player_id bigint NOT NULL UNIQUE,
  load_index numeric,
  fatigue_score numeric,
  matches_last_7_days integer,
  matches_last_30_days integer,
  minutes_last_7_days integer,
  minutes_last_30_days integer,
  transfers_last_12_months integer,
  avg_minutes_per_match numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  readiness_score numeric,
  importance_score numeric,
  goal_share_pct numeric,
  assist_share_pct numeric,
  minutes_share_pct numeric,
  CONSTRAINT player_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT player_intelligence_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.match_intelligence (
  id bigint NOT NULL DEFAULT nextval('match_intelligence_id_seq'::regclass),
  match_id bigint NOT NULL UNIQUE,
  home_readiness numeric,
  away_readiness numeric,
  readiness_gap numeric,
  congestion_factor numeric,
  home_rest_days numeric,
  away_rest_days numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  home_travel_distance_km numeric,
  away_travel_distance_km numeric,
  travel_advantage_score numeric,
  home_active_competitions integer DEFAULT 0,
  away_active_competitions integer DEFAULT 0,
  home_injury_score numeric,
  away_injury_score numeric,
  home_squad_stability numeric,
  away_squad_stability numeric,
  home_strength_rating numeric,
  away_strength_rating numeric,
  home_venue_advantage numeric,
  away_venue_advantage numeric,
  home_positional_depth numeric,
  away_positional_depth numeric,
  home_available_market_value bigint,
  away_available_market_value bigint,
  home_injured_market_value bigint,
  away_injured_market_value bigint,
  motivation_gap numeric,
  match_date timestamp with time zone,
  predicted_home_goals numeric,
  predicted_away_goals numeric,
  predicted_scorelines jsonb,
  confidence_score numeric,
  confidence_band text,
  win_probability_home numeric,
  win_probability_draw numeric,
  win_probability_away numeric,
  CONSTRAINT match_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT match_intelligence_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.team_fixture_load (
  id bigint NOT NULL DEFAULT nextval('team_fixture_load_id_seq'::regclass),
  team_id bigint NOT NULL,
  matches_last_7_days integer,
  matches_last_14_days integer,
  matches_last_30_days integer,
  avg_rest_days numeric,
  min_rest_days integer,
  congestion_score numeric,
  snapshot_date date NOT NULL,
  calculated_at timestamp with time zone DEFAULT now(),
  matches_next_7_days integer,
  matches_next_14_days integer,
  CONSTRAINT team_fixture_load_pkey PRIMARY KEY (id),
  CONSTRAINT team_fixture_load_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.stadiums (
  id bigint NOT NULL DEFAULT nextval('stadiums_id_seq'::regclass),
  external_id bigint UNIQUE,
  name text NOT NULL,
  city text,
  state_region text,
  country text NOT NULL,
  latitude numeric,
  longitude numeric,
  elevation_meters integer,
  timezone text,
  capacity integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stadiums_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_locations (
  team_id bigint NOT NULL,
  stadium_id bigint,
  city text,
  country text,
  latitude numeric,
  longitude numeric,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_locations_pkey PRIMARY KEY (team_id),
  CONSTRAINT fk_team_locations_team FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT fk_team_locations_stadium FOREIGN KEY (stadium_id) REFERENCES public.stadiums(id)
);
CREATE TABLE public.team_travel_load (
  id bigint NOT NULL DEFAULT nextval('team_travel_load_id_seq'::regclass),
  team_id bigint NOT NULL,
  snapshot_date date NOT NULL,
  km_last_7_days numeric DEFAULT 0,
  km_last_14_days numeric DEFAULT 0,
  km_last_30_days numeric DEFAULT 0,
  away_matches_last_7_days integer DEFAULT 0,
  away_matches_last_14_days integer DEFAULT 0,
  away_matches_last_30_days integer DEFAULT 0,
  avg_trip_distance_km numeric,
  travel_fatigue_score numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_travel_load_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_travel_load_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_travel_intelligence (
  id bigint NOT NULL DEFAULT nextval('match_travel_intelligence_id_seq'::regclass),
  match_id bigint NOT NULL UNIQUE,
  home_team_distance_km numeric,
  away_team_distance_km numeric,
  travel_advantage_km numeric,
  travel_advantage_team_id bigint,
  calculated_at timestamp with time zone DEFAULT now(),
  match_date timestamp with time zone,
  CONSTRAINT match_travel_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT fk_match_travel_match FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.player_injuries (
  id bigint NOT NULL DEFAULT nextval('player_injuries_id_seq'::regclass),
  player_id bigint NOT NULL,
  injury_reason text,
  injury_status text,
  expected_return_days integer,
  start_timestamp bigint,
  end_timestamp bigint,
  updated_timestamp bigint,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  days_out integer,
  injury_severity_score numeric,
  position_at_injury text,
  market_value_at_injury bigint,
  CONSTRAINT player_injuries_pkey PRIMARY KEY (id),
  CONSTRAINT fk_player_injuries_player FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.player_match_load (
  id bigint NOT NULL DEFAULT nextval('player_match_load_id_seq'::regclass),
  player_id bigint NOT NULL,
  match_id bigint,
  match_date date NOT NULL,
  minutes_played integer,
  started boolean DEFAULT false,
  substitute boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT player_match_load_pkey PRIMARY KEY (id),
  CONSTRAINT fk_player_match_load_player FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT fk_player_match_load_match FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.team_strength_ratings (
  id bigint NOT NULL DEFAULT nextval('team_strength_ratings_id_seq'::regclass),
  team_id bigint NOT NULL UNIQUE,
  league_position integer,
  points_per_game numeric,
  win_percentage numeric,
  strength_score numeric,
  market_value_eur bigint,
  calculated_at timestamp with time zone DEFAULT now(),
  lineup_versatility_score numeric,
  CONSTRAINT team_strength_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_strength_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_venue_performance (
  id bigint NOT NULL DEFAULT nextval('team_venue_performance_id_seq'::regclass),
  team_id bigint NOT NULL UNIQUE,
  home_matches integer DEFAULT 0,
  away_matches integer DEFAULT 0,
  home_points_per_game numeric,
  away_points_per_game numeric,
  home_win_pct numeric,
  away_win_pct numeric,
  home_goal_diff numeric,
  away_goal_diff numeric,
  venue_advantage_score numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_venue_performance_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_venue_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_weather (
  id bigint NOT NULL DEFAULT nextval('match_weather_id_seq'::regclass),
  match_id bigint UNIQUE,
  temperature_c numeric,
  humidity numeric,
  wind_speed_kmh numeric,
  weather_condition text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_weather_pkey PRIMARY KEY (id),
  CONSTRAINT fk_match_weather_match FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.team_position_depth (
  id bigint NOT NULL DEFAULT nextval('team_position_depth_id_seq'::regclass),
  team_id bigint NOT NULL,
  position_code text NOT NULL,
  player_count integer DEFAULT 0,
  injured_count integer DEFAULT 0,
  available_count integer DEFAULT 0,
  total_market_value bigint DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_position_depth_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_position_depth_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_transfer_intelligence (
  id bigint NOT NULL DEFAULT nextval('team_transfer_intelligence_id_seq'::regclass),
  team_id bigint NOT NULL UNIQUE,
  transfers_in integer DEFAULT 0,
  transfers_out integer DEFAULT 0,
  retained_players integer DEFAULT 0,
  retention_percentage numeric,
  transfer_activity_score numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_transfer_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_transfer_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.player_season_statistics (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  player_id bigint NOT NULL,
  team_id bigint NOT NULL,
  tournament_id bigint,
  season_external_id bigint NOT NULL,
  rating numeric,
  total_rating numeric,
  count_rating integer,
  appearances integer,
  matches_started integer,
  minutes_played integer,
  goals integer,
  assists integer,
  expected_goals numeric,
  expected_assists numeric,
  yellow_cards integer,
  red_cards integer,
  played_enough boolean DEFAULT false,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  accurate_passes integer,
  inaccurate_passes integer,
  total_passes integer,
  accurate_passes_pct numeric,
  accurate_own_half_passes integer,
  accurate_opposition_half_passes integer,
  accurate_final_third_passes integer,
  key_passes integer,
  accurate_long_balls integer,
  accurate_long_balls_pct numeric,
  total_long_balls integer,
  accurate_chipped_passes integer,
  total_chipped_passes integer,
  accurate_crosses integer,
  accurate_crosses_pct numeric,
  total_cross integer,
  pass_to_assist integer,
  total_attempt_assist integer,
  total_own_half_passes integer,
  total_opposition_half_passes integer,
  total_shots integer,
  shots_on_target integer,
  shots_off_target integer,
  shots_from_inside_box integer,
  shots_from_outside_box integer,
  goals_from_inside_box integer,
  goals_from_outside_box integer,
  headed_goals integer,
  left_foot_goals integer,
  right_foot_goals integer,
  goal_conversion_pct numeric,
  big_chances_created integer,
  big_chances_missed integer,
  hit_woodwork integer,
  shot_from_set_piece integer,
  free_kick_goal integer,
  successful_dribbles integer,
  successful_dribbles_pct numeric,
  total_contest integer,
  dispossessed integer,
  possession_lost integer,
  possession_won_att_third integer,
  touches integer,
  dribbled_past integer,
  was_fouled integer,
  fouls integer,
  offsides integer,
  tackles integer,
  tackles_won integer,
  tackles_won_pct numeric,
  interceptions integer,
  clearances integer,
  blocked_shots integer,
  ball_recovery integer,
  outfielder_blocks integer,
  error_lead_to_goal integer,
  error_lead_to_shot integer,
  ground_duels_won integer,
  ground_duels_won_pct numeric,
  aerial_duels_won integer,
  aerial_duels_won_pct numeric,
  aerial_lost integer,
  total_duels_won integer,
  total_duels_won_pct numeric,
  duel_lost integer,
  penalties_taken integer,
  penalty_goals integer,
  penalty_won integer,
  penalty_conceded integer,
  penalty_conversion_pct numeric,
  attempt_penalty_miss integer,
  attempt_penalty_post integer,
  attempt_penalty_target integer,
  set_piece_conversion_pct numeric,
  direct_red_cards integer,
  yellow_red_cards integer,
  own_goals integer,
  totw_appearances integer,
  saves integer,
  saves_caught integer,
  saves_parried integer,
  penalty_faced integer,
  penalty_save integer,
  saved_shots_inside_box integer,
  saved_shots_outside_box integer,
  goals_conceded integer,
  goals_conceded_inside_box integer,
  goals_conceded_outside_box integer,
  clean_sheet integer,
  punches integer,
  runs_out integer,
  successful_runs_out integer,
  high_claims integer,
  crosses_not_claimed integer,
  goal_kicks integer,
  kilometers_covered numeric,
  number_of_sprints integer,
  top_speed numeric,
  CONSTRAINT player_season_statistics_pkey PRIMARY KEY (id),
  CONSTRAINT player_season_statistics_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT player_season_statistics_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT player_season_statistics_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.team_season_statistics (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL,
  tournament_id bigint,
  season_external_id bigint NOT NULL,
  matches integer,
  goals_scored integer,
  goals_conceded integer,
  clean_sheets integer,
  avg_possession numeric,
  avg_rating numeric,
  total_passes integer,
  accurate_passes_pct numeric,
  duels_won_pct numeric,
  aerial_duels_won_pct numeric,
  tackles integer,
  interceptions integer,
  yellow_cards integer,
  red_cards integer,
  big_chances_created integer,
  big_chances_missed integer,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_season_statistics_pkey PRIMARY KEY (id),
  CONSTRAINT team_season_statistics_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_season_statistics_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.match_predicted_lineups (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  team_id bigint NOT NULL,
  player_id bigint NOT NULL,
  position_code text,
  rank_in_position integer,
  matches_started integer,
  confidence numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_predicted_lineups_pkey PRIMARY KEY (id),
  CONSTRAINT match_predicted_lineups_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_predicted_lineups_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT match_predicted_lineups_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.tournament_standings (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  tournament_id bigint NOT NULL,
  team_id bigint NOT NULL,
  season_external_id bigint NOT NULL,
  standings_type text NOT NULL DEFAULT 'total'::text,
  position integer,
  matches integer,
  wins integer,
  draws integer,
  losses integer,
  scores_for integer,
  scores_against integer,
  points integer,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tournament_standings_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_standings_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT tournament_standings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.platform_daily_summary (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  summary_date date NOT NULL UNIQUE,
  matches_today integer DEFAULT 0,
  competitions_today integer DEFAULT 0,
  teams_tracked integer DEFAULT 0,
  competitions_tracked integer DEFAULT 0,
  readiness_calculated_count integer DEFAULT 0,
  avg_readiness numeric,
  last_sync_at timestamp with time zone,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_daily_summary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_intelligence_history (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL,
  snapshot_date date NOT NULL,
  readiness_score numeric,
  form_index numeric,
  congestion_score numeric,
  travel_fatigue_score numeric,
  rest_days_avg numeric,
  squad_stability_score numeric,
  injury_burden_score numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_intelligence_history_pkey PRIMARY KEY (id),
  CONSTRAINT team_intelligence_history_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_signals (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  market text NOT NULL,
  signal_group text NOT NULL,
  signal_text text NOT NULL,
  direction text NOT NULL,
  strength integer NOT NULL,
  drivers text,
  data_source text,
  locked boolean DEFAULT false,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_signals_pkey PRIMARY KEY (id),
  CONSTRAINT match_signals_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.league_intelligence (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  tournament_id bigint NOT NULL UNIQUE,
  team_count integer DEFAULT 0,
  avg_readiness numeric,
  avg_form numeric,
  avg_congestion numeric,
  avg_travel_14d numeric,
  avg_rest_days numeric,
  avg_active_competitions numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT league_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT league_intelligence_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.team_fixture_difficulty (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  next_5_difficulty numeric,
  next_10_difficulty numeric,
  next_5_matches integer DEFAULT 0,
  next_10_matches integer DEFAULT 0,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_fixture_difficulty_pkey PRIMARY KEY (id),
  CONSTRAINT team_fixture_difficulty_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_momentum (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  momentum_score numeric,
  last_5_points integer,
  prior_5_points integer,
  trend text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_momentum_pkey PRIMARY KEY (id),
  CONSTRAINT team_momentum_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_goal_dependency (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  season_external_id bigint,
  total_goals integer,
  total_assists integer,
  top_scorer_player_id bigint,
  top_scorer_goals integer,
  top_scorer_pct numeric,
  top_2_scorers_pct numeric,
  top_scorer_no_backup boolean,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_goal_dependency_pkey PRIMARY KEY (id),
  CONSTRAINT team_goal_dependency_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_goal_dependency_top_scorer_fkey FOREIGN KEY (top_scorer_player_id) REFERENCES public.players(id)
);
CREATE TABLE public.team_injury_impact (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  injured_count integer,
  total_importance_lost numeric,
  goals_lost integer,
  assists_lost integer,
  no_replacement_positions text,
  worst_absence_player_id bigint,
  worst_absence_importance numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_injury_impact_pkey PRIMARY KEY (id),
  CONSTRAINT team_injury_impact_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_injury_impact_worst_fkey FOREIGN KEY (worst_absence_player_id) REFERENCES public.players(id)
);
CREATE TABLE public.readiness_history (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  match_external_id bigint NOT NULL,
  snapshot_at timestamp with time zone NOT NULL DEFAULT now(),
  match_date timestamp with time zone NOT NULL,
  readiness_formula_version text NOT NULL DEFAULT 'v1'::text,
  league_name text NOT NULL,
  home_team text NOT NULL,
  away_team text NOT NULL,
  home_team_id bigint NOT NULL,
  away_team_id bigint NOT NULL,
  home_readiness numeric NOT NULL,
  away_readiness numeric NOT NULL,
  predicted_gap numeric NOT NULL,
  predicted_pick text NOT NULL,
  confidence_pct numeric NOT NULL,
  squad_versatility numeric,
  defense_confidence_pct numeric,
  midfield_confidence_pct numeric,
  attack_confidence_pct numeric,
  result_linked_at timestamp with time zone,
  final_home_score integer,
  final_away_score integer,
  final_outcome text,
  pick_correct_strict boolean,
  pick_correct_lenient boolean,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT readiness_history_pkey PRIMARY KEY (id),
  CONSTRAINT readiness_history_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.league_gap_analytics (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  league_name text NOT NULL,
  gap_tier text NOT NULL,
  total_picks integer NOT NULL,
  hit_rate_strict numeric,
  hit_rate_lenient numeric,
  avg_winning_gap numeric,
  avg_losing_gap numeric,
  baseline_rate numeric,
  lift_over_baseline numeric,
  versatility_coverage numeric,
  computed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT league_gap_analytics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.league_gap_summary (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  league_name text NOT NULL UNIQUE,
  total_picks integer NOT NULL,
  hit_rate_strict numeric,
  hit_rate_lenient numeric,
  avg_winning_gap numeric,
  baseline_rate numeric,
  lift_over_baseline numeric,
  readiness_status text,
  meets_sample_gate boolean NOT NULL DEFAULT false,
  computed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT league_gap_summary_pkey PRIMARY KEY (id)
);