-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.countries (
  id bigint NOT NULL DEFAULT nextval('countries_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  alpha2 text,
  slug text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT countries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tournaments (
  id bigint NOT NULL DEFAULT nextval('tournaments_id_seq'::regclass),
  external_id bigint NOT NULL UNIQUE,
  name text NOT NULL,
  slug text,
  country_id bigint,
  category text,
  created_at timestamp with time zone DEFAULT now(),
  logo_storage_path text,
  CONSTRAINT tournaments_pkey PRIMARY KEY (id),
  CONSTRAINT tournaments_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id)
);
CREATE TABLE public.seasons (
  id bigint NOT NULL DEFAULT nextval('seasons_id_seq'::regclass),
  external_id bigint NOT NULL UNIQUE,
  name text,
  year text,
  tournament_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT seasons_pkey PRIMARY KEY (id),
  CONSTRAINT seasons_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.teams (
  id bigint NOT NULL DEFAULT nextval('teams_id_seq'::regclass),
  external_id bigint NOT NULL UNIQUE,
  name text NOT NULL,
  short_name text,
  country text,
  slug text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  stadium_id bigint,
  crest_storage_path text,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_stadium FOREIGN KEY (stadium_id) REFERENCES public.stadiums(id)
);
CREATE TABLE public.players (
  id bigint NOT NULL DEFAULT nextval('players_id_seq'::regclass),
  external_id bigint NOT NULL UNIQUE,
  name text NOT NULL,
  position text,
  nationality text,
  date_of_birth date,
  market_value bigint,
  team_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  preferred_foot text,
  contract_until date,
  height_cm integer,
  jersey_number integer,
  position_detailed text,
  current_injury boolean DEFAULT false,
  injury_status text,
  injury_reason text,
  injury_return_days integer,
  primary_position text,
  secondary_position text,
  tertiary_position text,
  nationality_code text,
  injury_expected_return_days integer,
  injury_end_timestamp bigint,
  injury_start_timestamp bigint,
  injury_updated_timestamp bigint,
  injury_severity_score numeric,
  short_name text,
  CONSTRAINT players_pkey PRIMARY KEY (id),
  CONSTRAINT players_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.matches (
  id bigint NOT NULL DEFAULT nextval('matches_id_seq'::regclass),
  external_match_id bigint NOT NULL UNIQUE,
  home_team_id bigint NOT NULL,
  away_team_id bigint NOT NULL,
  date timestamp with time zone NOT NULL,
  competition text,
  season text,
  status text NOT NULL DEFAULT 'scheduled'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  venue_id bigint,
  tournament_id bigint,
  season_id bigint,
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id),
  CONSTRAINT matches_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id),
  CONSTRAINT fk_match_venue FOREIGN KEY (venue_id) REFERENCES public.stadiums(id),
  CONSTRAINT matches_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT matches_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id)
);
CREATE TABLE public.match_results (
  id bigint NOT NULL DEFAULT nextval('match_results_id_seq'::regclass),
  match_id bigint NOT NULL UNIQUE,
  home_score integer,
  away_score integer,
  half_time_home_score integer,
  half_time_away_score integer,
  winner_team_id bigint,
  status text NOT NULL DEFAULT 'scheduled'::text,
  updated_at timestamp with time zone DEFAULT now(),
  match_date timestamp with time zone,
  CONSTRAINT match_results_pkey PRIMARY KEY (id),
  CONSTRAINT match_results_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_results_winner_team_id_fkey FOREIGN KEY (winner_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_squads_snapshot (
  id bigint NOT NULL DEFAULT nextval('team_squads_snapshot_id_seq'::regclass),
  team_id bigint NOT NULL,
  snapshot_date date NOT NULL,
  players_count integer,
  avg_age numeric,
  foreign_players_count integer,
  domestic_players_count integer,
  created_at timestamp with time zone DEFAULT now(),
  average_market_value bigint,
  injured_player_count integer DEFAULT 0,
  foreign_player_pct numeric,
  injured_player_pct numeric,
  CONSTRAINT team_squads_snapshot_pkey PRIMARY KEY (id),
  CONSTRAINT team_squads_snapshot_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.player_transfers (
  id bigint NOT NULL DEFAULT nextval('player_transfers_id_seq'::regclass),
  player_id bigint NOT NULL,
  from_team_id bigint,
  to_team_id bigint,
  transfer_date date NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  transfer_fee bigint,
  transfer_fee_currency text,
  transfer_type integer,
  source text DEFAULT 'squad_diff'::text,
  CONSTRAINT player_transfers_pkey PRIMARY KEY (id),
  CONSTRAINT player_transfers_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT player_transfers_from_team_id_fkey FOREIGN KEY (from_team_id) REFERENCES public.teams(id),
  CONSTRAINT player_transfers_to_team_id_fkey FOREIGN KEY (to_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_form_history (
  id bigint NOT NULL DEFAULT nextval('team_form_history_id_seq'::regclass),
  team_id bigint NOT NULL,
  match_id bigint NOT NULL,
  result character NOT NULL CHECK (result = ANY (ARRAY['W'::bpchar, 'D'::bpchar, 'L'::bpchar])) NOT VALI),
  goals_for integer,
  goals_against integer,
  points integer,
  created_at timestamp with time zone DEFAULT now(),
  match_date timestamp with time zone,
  is_home boolean,
  half_time_score_for integer,
  half_time_score_against integer,
  btts boolean,
  CONSTRAINT team_form_history_pkey PRIMARY KEY (id),
  CONSTRAINT team_form_history_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_form_history_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.team_intelligence (
  id bigint NOT NULL DEFAULT nextval('team_intelligence_id_seq'::regclass),
  team_id bigint NOT NULL UNIQUE,
  readiness_score numeric,
  fatigue_index numeric,
  rotation_pressure_index numeric,
  form_index numeric,
  last_5_points integer,
  last_10_points integer,
  congestion_score numeric,
  rest_days_avg numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  travel_fatigue_score numeric,
  travel_load_km numeric,
  active_competitions integer DEFAULT 0,
  squad_stability_score numeric,
  injury_burden_score numeric,
  squad_depth_score numeric,
  injured_market_value bigint DEFAULT 0,
  available_market_value bigint DEFAULT 0,
  lineup_versatility_score numeric,
  last_5_results text CHECK (last_5_results IS NULL OR last_5_results ~ '^[WDL]{1,5}$'::text),
  strengths ARRAY,
  weaknesses ARRAY,
  recommended_approach text,
  overall_rating integer,
  CONSTRAINT team_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT team_intelligence_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.player_intelligence (
  id bigint NOT NULL DEFAULT nextval('player_intelligence_id_seq'::regclass),
  player_id bigint NOT NULL UNIQUE,
  load_index numeric,
  fatigue_score numeric,
  matches_last_7_days integer,
  matches_last_30_days integer,
  minutes_last_7_days integer,
  minutes_last_30_days integer,
  transfers_last_12_months integer,
  avg_minutes_per_match numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  readiness_score numeric,
  importance_score numeric,
  goal_share_pct numeric,
  assist_share_pct numeric,
  minutes_share_pct numeric,
  player_strength_score integer,
  CONSTRAINT player_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT player_intelligence_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.match_intelligence (
  id bigint NOT NULL DEFAULT nextval('match_intelligence_id_seq'::regclass),
  match_id bigint NOT NULL UNIQUE,
  home_readiness numeric,
  away_readiness numeric,
  readiness_gap numeric,
  congestion_factor numeric,
  home_rest_days numeric,
  away_rest_days numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  home_travel_distance_km numeric,
  away_travel_distance_km numeric,
  travel_advantage_score numeric,
  home_active_competitions integer DEFAULT 0,
  away_active_competitions integer DEFAULT 0,
  home_injury_score numeric,
  away_injury_score numeric,
  home_squad_stability numeric,
  away_squad_stability numeric,
  home_strength_rating numeric,
  away_strength_rating numeric,
  home_venue_advantage numeric,
  away_venue_advantage numeric,
  home_positional_depth numeric,
  away_positional_depth numeric,
  home_available_market_value bigint,
  away_available_market_value bigint,
  home_injured_market_value bigint,
  away_injured_market_value bigint,
  motivation_gap numeric,
  match_date timestamp with time zone,
  predicted_home_goals numeric,
  predicted_away_goals numeric,
  predicted_scorelines jsonb,
  confidence_score numeric,
  confidence_band text,
  win_probability_home numeric,
  win_probability_draw numeric,
  win_probability_away numeric,
  net_battle_index numeric,
  home_xi_strength integer,
  away_xi_strength integer,
  CONSTRAINT match_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT match_intelligence_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.team_fixture_load (
  id bigint NOT NULL DEFAULT nextval('team_fixture_load_id_seq'::regclass),
  team_id bigint NOT NULL,
  matches_last_7_days integer,
  matches_last_14_days integer,
  matches_last_30_days integer,
  avg_rest_days numeric,
  min_rest_days integer,
  congestion_score numeric,
  snapshot_date date NOT NULL,
  calculated_at timestamp with time zone DEFAULT now(),
  matches_next_7_days integer,
  matches_next_14_days integer,
  CONSTRAINT team_fixture_load_pkey PRIMARY KEY (id),
  CONSTRAINT team_fixture_load_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.stadiums (
  id bigint NOT NULL DEFAULT nextval('stadiums_id_seq'::regclass),
  external_id bigint UNIQUE,
  name text NOT NULL,
  city text,
  state_region text,
  country text NOT NULL,
  latitude numeric,
  longitude numeric,
  elevation_meters integer,
  timezone text,
  capacity integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stadiums_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_locations (
  team_id bigint NOT NULL,
  stadium_id bigint,
  city text,
  country text,
  latitude numeric,
  longitude numeric,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_locations_pkey PRIMARY KEY (team_id),
  CONSTRAINT fk_team_locations_team FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT fk_team_locations_stadium FOREIGN KEY (stadium_id) REFERENCES public.stadiums(id)
);
CREATE TABLE public.team_travel_load (
  id bigint NOT NULL DEFAULT nextval('team_travel_load_id_seq'::regclass),
  team_id bigint NOT NULL,
  snapshot_date date NOT NULL,
  km_last_7_days numeric DEFAULT 0,
  km_last_14_days numeric DEFAULT 0,
  km_last_30_days numeric DEFAULT 0,
  away_matches_last_7_days integer DEFAULT 0,
  away_matches_last_14_days integer DEFAULT 0,
  away_matches_last_30_days integer DEFAULT 0,
  avg_trip_distance_km numeric,
  travel_fatigue_score numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_travel_load_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_travel_load_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_travel_intelligence (
  id bigint NOT NULL DEFAULT nextval('match_travel_intelligence_id_seq'::regclass),
  match_id bigint NOT NULL UNIQUE,
  home_team_distance_km numeric,
  away_team_distance_km numeric,
  travel_advantage_km numeric,
  travel_advantage_team_id bigint,
  calculated_at timestamp with time zone DEFAULT now(),
  match_date timestamp with time zone,
  CONSTRAINT match_travel_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT fk_match_travel_match FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.player_injuries (
  id bigint NOT NULL DEFAULT nextval('player_injuries_id_seq'::regclass),
  player_id bigint NOT NULL,
  injury_reason text,
  injury_status text,
  expected_return_days integer,
  start_timestamp bigint,
  end_timestamp bigint,
  updated_timestamp bigint,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  days_out integer,
  injury_severity_score numeric,
  position_at_injury text,
  market_value_at_injury bigint,
  CONSTRAINT player_injuries_pkey PRIMARY KEY (id),
  CONSTRAINT fk_player_injuries_player FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.player_match_load (
  id bigint NOT NULL DEFAULT nextval('player_match_load_id_seq'::regclass),
  player_id bigint NOT NULL,
  match_id bigint,
  match_date date NOT NULL,
  minutes_played integer,
  started boolean DEFAULT false,
  substitute boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT player_match_load_pkey PRIMARY KEY (id),
  CONSTRAINT fk_player_match_load_player FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT fk_player_match_load_match FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.team_strength_ratings (
  id bigint NOT NULL DEFAULT nextval('team_strength_ratings_id_seq'::regclass),
  team_id bigint NOT NULL UNIQUE,
  league_position integer,
  points_per_game numeric,
  win_percentage numeric,
  strength_score numeric,
  market_value_eur bigint,
  calculated_at timestamp with time zone DEFAULT now(),
  lineup_versatility_score numeric,
  CONSTRAINT team_strength_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_strength_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_venue_performance (
  id bigint NOT NULL DEFAULT nextval('team_venue_performance_id_seq'::regclass),
  team_id bigint NOT NULL UNIQUE,
  home_matches integer DEFAULT 0,
  away_matches integer DEFAULT 0,
  home_points_per_game numeric,
  away_points_per_game numeric,
  home_win_pct numeric,
  away_win_pct numeric,
  home_goal_diff numeric,
  away_goal_diff numeric,
  venue_advantage_score numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_venue_performance_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_venue_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_weather (
  id bigint NOT NULL DEFAULT nextval('match_weather_id_seq'::regclass),
  match_id bigint UNIQUE,
  temperature_c numeric,
  humidity numeric,
  wind_speed_kmh numeric,
  weather_condition text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_weather_pkey PRIMARY KEY (id),
  CONSTRAINT fk_match_weather_match FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.team_position_depth (
  id bigint NOT NULL DEFAULT nextval('team_position_depth_id_seq'::regclass),
  team_id bigint NOT NULL,
  position_code text NOT NULL,
  player_count integer DEFAULT 0,
  injured_count integer DEFAULT 0,
  available_count integer DEFAULT 0,
  total_market_value bigint DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  strength_score integer,
  quality_rating text,
  depth_rating text,
  CONSTRAINT team_position_depth_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_position_depth_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_transfer_intelligence (
  id bigint NOT NULL DEFAULT nextval('team_transfer_intelligence_id_seq'::regclass),
  team_id bigint NOT NULL UNIQUE,
  transfers_in integer DEFAULT 0,
  transfers_out integer DEFAULT 0,
  retained_players integer DEFAULT 0,
  retention_percentage numeric,
  transfer_activity_score numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_transfer_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT fk_team_transfer_team FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.player_season_statistics (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  player_id bigint NOT NULL,
  team_id bigint NOT NULL,
  tournament_id bigint,
  season_external_id bigint NOT NULL,
  rating numeric,
  total_rating numeric,
  count_rating integer,
  appearances integer,
  matches_started integer,
  minutes_played integer,
  goals integer,
  assists integer,
  expected_goals numeric,
  expected_assists numeric,
  yellow_cards integer,
  red_cards integer,
  played_enough boolean DEFAULT false,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  accurate_passes integer,
  inaccurate_passes integer,
  total_passes integer,
  accurate_passes_pct numeric,
  accurate_own_half_passes integer,
  accurate_opposition_half_passes integer,
  accurate_final_third_passes integer,
  key_passes integer,
  accurate_long_balls integer,
  accurate_long_balls_pct numeric,
  total_long_balls integer,
  accurate_chipped_passes integer,
  total_chipped_passes integer,
  accurate_crosses integer,
  accurate_crosses_pct numeric,
  total_cross integer,
  pass_to_assist integer,
  total_attempt_assist integer,
  total_own_half_passes integer,
  total_opposition_half_passes integer,
  total_shots integer,
  shots_on_target integer,
  shots_off_target integer,
  shots_from_inside_box integer,
  shots_from_outside_box integer,
  goals_from_inside_box integer,
  goals_from_outside_box integer,
  headed_goals integer,
  left_foot_goals integer,
  right_foot_goals integer,
  goal_conversion_pct numeric,
  big_chances_created integer,
  big_chances_missed integer,
  hit_woodwork integer,
  shot_from_set_piece integer,
  free_kick_goal integer,
  successful_dribbles integer,
  successful_dribbles_pct numeric,
  total_contest integer,
  dispossessed integer,
  possession_lost integer,
  possession_won_att_third integer,
  touches integer,
  dribbled_past integer,
  was_fouled integer,
  fouls integer,
  offsides integer,
  tackles integer,
  tackles_won integer,
  tackles_won_pct numeric,
  interceptions integer,
  clearances integer,
  blocked_shots integer,
  ball_recovery integer,
  outfielder_blocks integer,
  error_lead_to_goal integer,
  error_lead_to_shot integer,
  ground_duels_won integer,
  ground_duels_won_pct numeric,
  aerial_duels_won integer,
  aerial_duels_won_pct numeric,
  aerial_lost integer,
  total_duels_won integer,
  total_duels_won_pct numeric,
  duel_lost integer,
  penalties_taken integer,
  penalty_goals integer,
  penalty_won integer,
  penalty_conceded integer,
  penalty_conversion_pct numeric,
  attempt_penalty_miss integer,
  attempt_penalty_post integer,
  attempt_penalty_target integer,
  set_piece_conversion_pct numeric,
  direct_red_cards integer,
  yellow_red_cards integer,
  own_goals integer,
  totw_appearances integer,
  saves integer,
  saves_caught integer,
  saves_parried integer,
  penalty_faced integer,
  penalty_save integer,
  saved_shots_inside_box integer,
  saved_shots_outside_box integer,
  goals_conceded integer,
  goals_conceded_inside_box integer,
  goals_conceded_outside_box integer,
  clean_sheet integer,
  punches integer,
  runs_out integer,
  successful_runs_out integer,
  high_claims integer,
  crosses_not_claimed integer,
  goal_kicks integer,
  kilometers_covered numeric,
  number_of_sprints integer,
  top_speed numeric,
  CONSTRAINT player_season_statistics_pkey PRIMARY KEY (id),
  CONSTRAINT player_season_statistics_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT player_season_statistics_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT player_season_statistics_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.team_season_statistics (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL,
  tournament_id bigint,
  season_external_id bigint NOT NULL,
  matches integer,
  goals_scored integer,
  goals_conceded integer,
  clean_sheets integer,
  avg_possession numeric,
  avg_rating numeric,
  total_passes integer,
  accurate_passes_pct numeric,
  duels_won_pct numeric,
  aerial_duels_won_pct numeric,
  tackles integer,
  interceptions integer,
  yellow_cards integer,
  red_cards integer,
  big_chances_created integer,
  big_chances_missed integer,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  shots integer,
  shots_on_target integer,
  shots_off_target integer,
  big_chances integer,
  shots_from_inside_the_box integer,
  shots_against integer,
  shots_on_target_against integer,
  big_chances_against integer,
  corners_against integer,
  accurate_opposition_half_passes_pct numeric,
  fouls integer,
  offsides integer,
  CONSTRAINT team_season_statistics_pkey PRIMARY KEY (id),
  CONSTRAINT team_season_statistics_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_season_statistics_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.match_predicted_lineups (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  team_id bigint NOT NULL,
  player_id bigint NOT NULL,
  position_code text,
  rank_in_position integer,
  matches_started integer,
  confidence numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_predicted_lineups_pkey PRIMARY KEY (id),
  CONSTRAINT match_predicted_lineups_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_predicted_lineups_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT match_predicted_lineups_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.tournament_standings (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  tournament_id bigint NOT NULL,
  team_id bigint NOT NULL,
  season_external_id bigint NOT NULL,
  standings_type text NOT NULL DEFAULT 'total'::text,
  position integer,
  matches integer,
  wins integer,
  draws integer,
  losses integer,
  scores_for integer,
  scores_against integer,
  points integer,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tournament_standings_pkey PRIMARY KEY (id),
  CONSTRAINT tournament_standings_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id),
  CONSTRAINT tournament_standings_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.platform_daily_summary (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  summary_date date NOT NULL UNIQUE,
  matches_today integer DEFAULT 0,
  competitions_today integer DEFAULT 0,
  teams_tracked integer DEFAULT 0,
  competitions_tracked integer DEFAULT 0,
  readiness_calculated_count integer DEFAULT 0,
  avg_readiness numeric,
  last_sync_at timestamp with time zone,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_daily_summary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_intelligence_history (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL,
  snapshot_date date NOT NULL,
  readiness_score numeric,
  form_index numeric,
  congestion_score numeric,
  travel_fatigue_score numeric,
  rest_days_avg numeric,
  squad_stability_score numeric,
  injury_burden_score numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_intelligence_history_pkey PRIMARY KEY (id),
  CONSTRAINT team_intelligence_history_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_signals (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  market text NOT NULL,
  signal_group text NOT NULL,
  signal_text text NOT NULL,
  direction text NOT NULL,
  strength integer NOT NULL,
  drivers text,
  data_source text,
  locked boolean DEFAULT false,
  calculated_at timestamp with time zone DEFAULT now(),
  rule_key text,
  CONSTRAINT match_signals_pkey PRIMARY KEY (id),
  CONSTRAINT match_signals_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.league_intelligence (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  tournament_id bigint NOT NULL UNIQUE,
  team_count integer DEFAULT 0,
  avg_readiness numeric,
  avg_form numeric,
  avg_congestion numeric,
  avg_travel_14d numeric,
  avg_rest_days numeric,
  avg_active_competitions numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT league_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT league_intelligence_tournament_id_fkey FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id)
);
CREATE TABLE public.team_fixture_difficulty (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  next_5_difficulty numeric,
  next_10_difficulty numeric,
  next_5_matches integer DEFAULT 0,
  next_10_matches integer DEFAULT 0,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_fixture_difficulty_pkey PRIMARY KEY (id),
  CONSTRAINT team_fixture_difficulty_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_momentum (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  momentum_score numeric,
  last_5_points integer,
  prior_5_points integer,
  trend text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_momentum_pkey PRIMARY KEY (id),
  CONSTRAINT team_momentum_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_goal_dependency (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  season_external_id bigint,
  total_goals integer,
  total_assists integer,
  top_scorer_player_id bigint,
  top_scorer_goals integer,
  top_scorer_pct numeric,
  top_2_scorers_pct numeric,
  top_scorer_no_backup boolean,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_goal_dependency_pkey PRIMARY KEY (id),
  CONSTRAINT team_goal_dependency_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_goal_dependency_top_scorer_fkey FOREIGN KEY (top_scorer_player_id) REFERENCES public.players(id)
);
CREATE TABLE public.team_injury_impact (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  injured_count integer,
  total_importance_lost numeric,
  goals_lost integer,
  assists_lost integer,
  no_replacement_positions text,
  worst_absence_player_id bigint,
  worst_absence_importance numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_injury_impact_pkey PRIMARY KEY (id),
  CONSTRAINT team_injury_impact_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_injury_impact_worst_fkey FOREIGN KEY (worst_absence_player_id) REFERENCES public.players(id)
);
CREATE TABLE public.readiness_history (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  match_external_id bigint NOT NULL,
  snapshot_at timestamp with time zone NOT NULL DEFAULT now(),
  match_date timestamp with time zone NOT NULL,
  readiness_formula_version text NOT NULL DEFAULT 'v1'::text,
  league_name text NOT NULL,
  home_team text NOT NULL,
  away_team text NOT NULL,
  home_team_id bigint NOT NULL,
  away_team_id bigint NOT NULL,
  home_readiness numeric NOT NULL,
  away_readiness numeric NOT NULL,
  predicted_gap numeric NOT NULL,
  predicted_pick text NOT NULL,
  confidence_pct numeric NOT NULL,
  squad_versatility numeric,
  defense_confidence_pct numeric,
  midfield_confidence_pct numeric,
  attack_confidence_pct numeric,
  result_linked_at timestamp with time zone,
  final_home_score integer,
  final_away_score integer,
  final_outcome text,
  pick_correct_strict boolean,
  pick_correct_lenient boolean,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT readiness_history_pkey PRIMARY KEY (id),
  CONSTRAINT readiness_history_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.league_gap_analytics (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  league_name text NOT NULL,
  gap_tier text NOT NULL,
  total_picks integer NOT NULL,
  hit_rate_strict numeric,
  hit_rate_lenient numeric,
  avg_winning_gap numeric,
  avg_losing_gap numeric,
  baseline_rate numeric,
  lift_over_baseline numeric,
  versatility_coverage numeric,
  computed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT league_gap_analytics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.league_gap_summary (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  league_name text NOT NULL UNIQUE,
  total_picks integer NOT NULL,
  hit_rate_strict numeric,
  hit_rate_lenient numeric,
  avg_winning_gap numeric,
  baseline_rate numeric,
  lift_over_baseline numeric,
  readiness_status text,
  meets_sample_gate boolean NOT NULL DEFAULT false,
  computed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT league_gap_summary_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_match_snapshots (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  team_id bigint NOT NULL,
  is_home boolean,
  league_position_before integer,
  points_before integer NOT NULL DEFAULT 0,
  games_played_before integer NOT NULL DEFAULT 0,
  goal_diff_before integer NOT NULL DEFAULT 0,
  ppg_before numeric,
  points_last5_before integer,
  form_rating_before numeric,
  readiness_before numeric,
  strength_rating_before numeric,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_match_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT team_match_snapshots_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT team_match_snapshots_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_opponent_context (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  team_id bigint NOT NULL,
  opponent_team_id bigint NOT NULL,
  opponent_position_before integer,
  opponent_points_before integer,
  opponent_ppg_before numeric,
  opponent_form_before integer,
  opponent_rank_band text CHECK (opponent_rank_band = ANY (ARRAY['top'::text, 'middle'::text, 'bottom'::text])),
  opponent_quality_score numeric,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT match_opponent_context_pkey PRIMARY KEY (id),
  CONSTRAINT match_opponent_context_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_opponent_context_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT match_opponent_context_opponent_team_id_fkey FOREIGN KEY (opponent_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_form_quality (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  window_matches integer NOT NULL DEFAULT 0,
  opponent_adjusted_form numeric,
  strength_of_schedule numeric,
  ppg_vs_top numeric,
  matches_vs_top integer NOT NULL DEFAULT 0,
  ppg_vs_middle numeric,
  matches_vs_middle integer NOT NULL DEFAULT 0,
  ppg_vs_bottom numeric,
  matches_vs_bottom integer NOT NULL DEFAULT 0,
  giant_killer_score numeric,
  flat_track_bully_score numeric,
  expected_points numeric,
  actual_points integer,
  performance_delta numeric,
  volatility numeric,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_form_quality_pkey PRIMARY KEY (id),
  CONSTRAINT team_form_quality_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_risk_intelligence (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  risk_score integer CHECK (risk_score >= 0 AND risk_score <= 100),
  risk_band text CHECK (risk_band = ANY (ARRAY['LOW'::text, 'MEDIUM'::text, 'HIGH'::text])),
  predictability_score integer CHECK (predictability_score >= 0 AND predictability_score <= 100),
  risk_factors jsonb NOT NULL DEFAULT '[]'::jsonb,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT match_risk_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT match_risk_intelligence_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.match_opportunity (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  opportunity_score integer CHECK (opportunity_score >= 0 AND opportunity_score <= 100),
  executive_brief text,
  signals jsonb NOT NULL DEFAULT '[]'::jsonb,
  warnings jsonb NOT NULL DEFAULT '[]'::jsonb,
  score_components jsonb NOT NULL DEFAULT '{}'::jsonb,
  calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT match_opportunity_pkey PRIMARY KEY (id),
  CONSTRAINT match_opportunity_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.signal_backtests (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  rule_key text NOT NULL,
  market text NOT NULL,
  sample_size integer NOT NULL,
  hits integer NOT NULL,
  hit_rate numeric NOT NULL,
  baseline_rate numeric NOT NULL,
  lift numeric NOT NULL,
  is_calibrated boolean NOT NULL DEFAULT false,
  window_days integer,
  notes text,
  evaluated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT signal_backtests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_betting_intelligence (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL,
  season_external_id bigint,
  attack_rating integer,
  defence_rating integer,
  team_quality_score integer,
  finishing_efficiency numeric,
  shot_accuracy numeric,
  shot_conversion_rate numeric,
  big_chance_conversion numeric,
  goal_creation_score integer,
  goal_prevention_score integer,
  defensive_fragility_score integer,
  clean_sheet_reliability numeric,
  attack_sustainability_score integer,
  consistency_score integer,
  volatility_score integer,
  predictability_score integer,
  sustainability_score integer,
  overperformance_score numeric,
  underperformance_score numeric,
  home_attack_rating integer,
  home_defence_rating integer,
  away_attack_rating integer,
  away_defence_rating integer,
  winner_market_score integer,
  goals_market_score integer,
  btts_score integer,
  cards_market_score integer,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_betting_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT team_betting_intelligence_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_playing_style (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  playing_style text,
  possession_score integer,
  passing_style text,
  attacking_style text,
  defensive_style text,
  style_confidence integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_playing_style_pkey PRIMARY KEY (id),
  CONSTRAINT team_playing_style_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_motivation (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  overall_motivation_score integer,
  motivation_band text,
  momentum_factor integer,
  quality_factor integer,
  venue_factor integer,
  fatigue_factor integer,
  external_motivation integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_motivation_pkey PRIMARY KEY (id),
  CONSTRAINT team_motivation_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_strength_dashboard (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  overall_rating integer,
  attack_rating integer,
  midfield_rating integer,
  defense_rating integer,
  set_piece_rating integer,
  tactical_rating integer,
  experience_rating integer,
  form_trend text,
  form_rating integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_strength_dashboard_pkey PRIMARY KEY (id),
  CONSTRAINT team_strength_dashboard_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_strengths (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL,
  strength_type text NOT NULL,
  description text NOT NULL,
  score integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_strengths_pkey PRIMARY KEY (id),
  CONSTRAINT team_strengths_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_weaknesses (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL,
  weakness_type text NOT NULL,
  description text NOT NULL,
  score integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_weaknesses_pkey PRIMARY KEY (id),
  CONSTRAINT team_weaknesses_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.player_match_impact (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  player_id bigint NOT NULL,
  impact_score integer,
  importance_score integer,
  readiness_score integer,
  fatigue_score integer,
  form_rating integer,
  goal_threat integer,
  assist_threat integer,
  defensive_contribution integer,
  creativity_score integer,
  experience_score integer,
  big_game_performance integer,
  matchup_advantage integer,
  matchup_disadvantage integer,
  impact_band text,
  expected_contribution text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT player_match_impact_pkey PRIMARY KEY (id),
  CONSTRAINT player_match_impact_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT player_match_impact_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.player_matchup (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  player_id bigint NOT NULL,
  opponent_player_id bigint NOT NULL,
  advantage_score integer,
  advantage_type text,
  matchup_notes text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT player_matchup_pkey PRIMARY KEY (id),
  CONSTRAINT player_matchup_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT player_matchup_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id),
  CONSTRAINT player_matchup_opponent_player_id_fkey FOREIGN KEY (opponent_player_id) REFERENCES public.players(id)
);
CREATE TABLE public.match_positional_matchups (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  position_code text NOT NULL,
  home_player_id bigint,
  away_player_id bigint,
  home_impact_score integer,
  away_impact_score integer,
  advantage_score integer,
  advantage_team_id bigint,
  advantage_type text,
  matchup_description text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_positional_matchups_pkey PRIMARY KEY (id),
  CONSTRAINT match_positional_matchups_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_positional_matchups_home_player_id_fkey FOREIGN KEY (home_player_id) REFERENCES public.players(id),
  CONSTRAINT match_positional_matchups_away_player_id_fkey FOREIGN KEY (away_player_id) REFERENCES public.players(id),
  CONSTRAINT match_positional_matchups_advantage_team_id_fkey FOREIGN KEY (advantage_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_key_battles (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  battle_id text NOT NULL,
  title text NOT NULL,
  description text,
  home_player_id bigint,
  away_player_id bigint,
  home_advantage_score integer,
  away_advantage_score integer,
  importance_score integer,
  expected_impact text,
  battle_outcome_prediction text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_key_battles_pkey PRIMARY KEY (id),
  CONSTRAINT match_key_battles_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_key_battles_home_player_id_fkey FOREIGN KEY (home_player_id) REFERENCES public.players(id),
  CONSTRAINT match_key_battles_away_player_id_fkey FOREIGN KEY (away_player_id) REFERENCES public.players(id)
);
CREATE TABLE public.match_tactical_advantages (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  advantage_type text NOT NULL,
  description text,
  home_advantage_score integer,
  away_advantage_score integer,
  net_advantage integer,
  advantage_team_id bigint,
  confidence_score integer,
  tactical_notes text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_tactical_advantages_pkey PRIMARY KEY (id),
  CONSTRAINT match_tactical_advantages_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_tactical_advantages_advantage_team_id_fkey FOREIGN KEY (advantage_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_match_impact (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  team_id bigint NOT NULL,
  overall_impact_score integer,
  attack_strength integer,
  midfield_control integer,
  defensive_strength integer,
  set_piece_threat integer,
  experience_level integer,
  form_trend integer,
  injury_impact integer,
  tactical_versatility integer,
  match_specific_boost integer,
  confidence_level integer,
  advantage_band text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_match_impact_pkey PRIMARY KEY (id),
  CONSTRAINT team_match_impact_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT team_match_impact_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_impact_advantage (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_advantage_score integer,
  away_advantage_score integer,
  advantage_margin integer,
  advantage_team_id bigint,
  key_advantages ARRAY,
  key_disadvantages ARRAY,
  confidence_score integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_impact_advantage_pkey PRIMARY KEY (id),
  CONSTRAINT match_impact_advantage_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_impact_advantage_advantage_team_id_fkey FOREIGN KEY (advantage_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_performance_comparison (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_team_id bigint NOT NULL,
  away_team_id bigint NOT NULL,
  overall_home_score integer,
  overall_away_score integer,
  overall_advantage integer,
  overall_advantage_team_id bigint,
  attacking_home_score integer,
  attacking_away_score integer,
  attacking_advantage integer,
  defensive_home_score integer,
  defensive_away_score integer,
  defensive_advantage integer,
  midfield_home_score integer,
  midfield_away_score integer,
  midfield_advantage integer,
  tactical_home_score integer,
  tactical_away_score integer,
  tactical_advantage integer,
  set_piece_home_score integer,
  set_piece_away_score integer,
  set_piece_advantage integer,
  form_home_score integer,
  form_away_score integer,
  form_advantage integer,
  home_win_probability numeric,
  draw_probability numeric,
  away_win_probability numeric,
  predicted_winner_id bigint,
  prediction_confidence integer,
  expected_goal_difference numeric,
  most_likely_score text,
  match_significance integer,
  confidence_band text,
  home_goals integer,
  away_goals integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_performance_comparison_pkey PRIMARY KEY (id),
  CONSTRAINT match_performance_comparison_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_performance_comparison_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id),
  CONSTRAINT match_performance_comparison_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id),
  CONSTRAINT match_performance_comparison_overall_advantage_team_id_fkey FOREIGN KEY (overall_advantage_team_id) REFERENCES public.teams(id),
  CONSTRAINT match_performance_comparison_predicted_winner_id_fkey FOREIGN KEY (predicted_winner_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_impact_summary (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  significance_score integer,
  importance_band text,
  rivalry_score integer,
  momentum_at_stake integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_impact_summary_pkey PRIMARY KEY (id),
  CONSTRAINT match_impact_summary_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.team_versatility (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  team_id bigint NOT NULL,
  overall_versatility_score integer,
  tactical_versatility_score integer,
  positional_versatility_score integer,
  formation_flexibility_score integer,
  player_adaptability_score integer,
  system_compatibility_score integer,
  versatility_band text,
  strengths ARRAY,
  weaknesses ARRAY,
  preferred_formations ARRAY,
  alternative_formations ARRAY,
  formation_changes_per_match numeric,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_versatility_pkey PRIMARY KEY (id),
  CONSTRAINT team_versatility_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT team_versatility_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.versatility_advantage (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  advantage_score integer,
  advantage_team_id bigint,
  advantage_margin integer,
  advantage_band text,
  key_advantages ARRAY,
  key_disadvantages ARRAY,
  confidence_score integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT versatility_advantage_pkey PRIMARY KEY (id),
  CONSTRAINT versatility_advantage_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT versatility_advantage_advantage_team_id_fkey FOREIGN KEY (advantage_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.tactical_flexibility (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_flexibility_score integer,
  away_flexibility_score integer,
  home_system_count integer,
  away_system_count integer,
  home_formation_adaptability integer,
  away_formation_adaptability integer,
  home_in_game_adaptability integer,
  away_in_game_adaptability integer,
  flexibility_advantage integer,
  flexibility_notes text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tactical_flexibility_pkey PRIMARY KEY (id),
  CONSTRAINT tactical_flexibility_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.position_adaptability (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_position_versatility integer,
  away_position_versatility integer,
  home_multi_position_players integer,
  away_multi_position_players integer,
  home_utility_players integer,
  away_utility_players integer,
  home_specialist_players integer,
  away_specialist_players integer,
  adaptability_advantage integer,
  position_coverage_score integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT position_adaptability_pkey PRIMARY KEY (id),
  CONSTRAINT position_adaptability_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.formation_options (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_available_formations ARRAY,
  away_available_formations ARRAY,
  home_primary_formation text,
  away_primary_formation text,
  home_secondary_formation text,
  away_secondary_formation text,
  home_tertiary_formation text,
  away_tertiary_formation text,
  home_formation_confidence integer,
  away_formation_confidence integer,
  formation_advantage integer,
  formation_notes text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT formation_options_pkey PRIMARY KEY (id),
  CONSTRAINT formation_options_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.substitution_impact (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_bench_strength integer,
  away_bench_strength integer,
  home_substitution_quality integer,
  away_substitution_quality integer,
  home_tactical_sub_options integer,
  away_tactical_sub_options integer,
  home_game_changers integer,
  away_game_changers integer,
  home_depth_score integer,
  away_depth_score integer,
  substitution_advantage integer,
  impact_notes text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT substitution_impact_pkey PRIMARY KEY (id),
  CONSTRAINT substitution_impact_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.injury_adaptability (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_injury_resilience integer,
  away_injury_resilience integer,
  home_position_redundancy integer,
  away_position_redundancy integer,
  home_cover_quality integer,
  away_cover_quality integer,
  home_system_flexibility_under_injury integer,
  away_system_flexibility_under_injury integer,
  home_emergency_cover_score integer,
  away_emergency_cover_score integer,
  adaptability_under_injury integer,
  resilience_notes text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT injury_adaptability_pkey PRIMARY KEY (id),
  CONSTRAINT injury_adaptability_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.player_versatility (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  player_id bigint NOT NULL UNIQUE,
  positions_played ARRAY,
  primary_position_rating integer,
  secondary_position_rating integer,
  tertiary_position_rating integer,
  versatility_score integer,
  adaptability_score integer,
  utility_rating integer,
  games_at_position integer,
  position_rating integer,
  overall_versatility integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT player_versatility_pkey PRIMARY KEY (id),
  CONSTRAINT player_versatility_player_id_fkey FOREIGN KEY (player_id) REFERENCES public.players(id)
);
CREATE TABLE public.position_coverage (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL,
  position_code text NOT NULL,
  position_name text,
  primary_players ARRAY,
  secondary_players ARRAY,
  total_coverage integer,
  coverage_quality integer,
  depth_rating text,
  emergency_cover text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT position_coverage_pkey PRIMARY KEY (id),
  CONSTRAINT position_coverage_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.squad_depth (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  team_id bigint NOT NULL,
  overall_depth_score integer,
  depth_rating text,
  starting_xi_quality integer,
  bench_quality integer,
  reserve_quality integer,
  quality_drop_off integer,
  coverage_completeness integer,
  position_balance integer,
  experience_distribution jsonb,
  age_profile jsonb,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT squad_depth_pkey PRIMARY KEY (id),
  CONSTRAINT squad_depth_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT squad_depth_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.match_squad_depth_comparison (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_team_id bigint NOT NULL,
  away_team_id bigint NOT NULL,
  home_overall_depth_score integer,
  away_overall_depth_score integer,
  home_depth_rating text,
  away_depth_rating text,
  home_quality_drop_off integer,
  away_quality_drop_off integer,
  depth_advantage_score integer,
  depth_advantage_team_id bigint,
  depth_advantage_margin integer,
  depth_advantage_band text,
  home_rotation_capability integer,
  away_rotation_capability integer,
  home_substitution_impact integer,
  away_substitution_impact integer,
  rotation_advantage integer,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_squad_depth_comparison_pkey PRIMARY KEY (id),
  CONSTRAINT match_squad_depth_comparison_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT match_squad_depth_comparison_home_team_id_fkey FOREIGN KEY (home_team_id) REFERENCES public.teams(id),
  CONSTRAINT match_squad_depth_comparison_away_team_id_fkey FOREIGN KEY (away_team_id) REFERENCES public.teams(id),
  CONSTRAINT match_squad_depth_comparison_depth_advantage_team_id_fkey FOREIGN KEY (depth_advantage_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.position_depth_comparison (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  position_code text NOT NULL,
  position_name text,
  home_depth_score integer,
  away_depth_score integer,
  home_quality integer,
  away_quality integer,
  home_count integer,
  away_count integer,
  advantage_team_id bigint,
  advantage_margin integer,
  depth_notes text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT position_depth_comparison_pkey PRIMARY KEY (id),
  CONSTRAINT position_depth_comparison_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT position_depth_comparison_advantage_team_id_fkey FOREIGN KEY (advantage_team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.team_tactical_variations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  team_id bigint NOT NULL UNIQUE,
  formation_history ARRAY,
  tactical_patterns ARRAY,
  system_effectiveness ARRAY,
  adaptability_score jsonb,
  game_state_adaptations ARRAY,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_tactical_variations_pkey PRIMARY KEY (id),
  CONSTRAINT team_tactical_variations_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.formation_analysis (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL,
  team_id bigint NOT NULL,
  primary_formation text NOT NULL,
  secondary_formation text,
  tertiary_formation text,
  formation_confidence integer,
  formation_variations ARRAY,
  preferred_style text,
  alternative_styles ARRAY,
  formation_strengths ARRAY,
  formation_weaknesses ARRAY,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT formation_analysis_pkey PRIMARY KEY (id),
  CONSTRAINT formation_analysis_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id),
  CONSTRAINT formation_analysis_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.formation_matchup (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_formation_vs_away text,
  away_formation_vs_home text,
  matchup_effectiveness integer,
  home_advantages ARRAY,
  away_advantages ARRAY,
  neutral_areas ARRAY,
  key_matchups ARRAY,
  tactical_notes text,
  calculated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT formation_matchup_pkey PRIMARY KEY (id),
  CONSTRAINT formation_matchup_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);
CREATE TABLE public.match_half_time_intelligence (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  match_id bigint NOT NULL UNIQUE,
  home_ht_win_prob numeric,
  draw_ht_prob numeric,
  away_ht_win_prob numeric,
  predicted_ht_goals_home numeric,
  predicted_ht_goals_away numeric,
  hh_prob numeric,
  hd_prob numeric,
  ha_prob numeric,
  dh_prob numeric,
  dd_prob numeric,
  da_prob numeric,
  ah_prob numeric,
  ad_prob numeric,
  aa_prob numeric,
  home_2h_goals numeric,
  away_2h_goals numeric,
  over_0_5_2h_prob numeric,
  over_1_5_2h_prob numeric,
  btts_2h_prob numeric,
  confidence_score integer,
  confidence_band text,
  calculated_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT match_half_time_intelligence_pkey PRIMARY KEY (id),
  CONSTRAINT match_half_time_intelligence_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id)
);