// ─────────────────────────────────────────────────────────────────────────────
// PIPELINE RUNS — operations.pipeline_run
//
// A pipeline EXECUTION owns exactly one pipeline_run. Every attributed stage
// within it owns one pipeline_job_run (jobLifecycle.ts). The run is the outer
// bracket; the jobs are the stages inside it.
//
// WHY AsyncLocalStorage RATHER THAN A PARAMETER
// S-1's public contract is fixed: withRun(role, jobKey, fn, options). It may not
// be redesigned, and it takes no run argument. The run therefore has to reach
// the lifecycle some other way, and an ambient context is the only mechanism
// that does not change the signature every caller already uses.
//
// AsyncLocalStorage propagates across await boundaries correctly, which a module
// global would not: two pipelines running concurrently in one process each see
// their own run, and neither can observe the other's. The concurrency test in
// operations.test.ts asserts exactly that.
//
// WHY A RUN IS CREATED IMPLICITLY WHEN NONE IS ACTIVE
// A stage invoked directly — from the CLI, from a test — still needs a run,
// because pipeline_job_run.pipeline_run_id is NOT NULL and the composite foreign
// key to pipeline_run admits no exception. Rather than fail such a call, an
// implicit single-stage run is opened around it. The trigger kind is MANUAL,
// which is what it is.
// ─────────────────────────────────────────────────────────────────────────────

import { AsyncLocalStorage } from 'node:async_hooks';
import type { Pool, PoolClient } from 'pg';
import { poolFor } from '../db/pool';
import type { PipelineRole } from '../db/roles';
import { logger } from '../../utils/logger';

/**
 * How a run came to be started. Values are fixed by
 * ck_pipeline_run__trigger_known and are not extensible from the application.
 */
export type TriggerKind = 'SCHEDULED' | 'MANUAL' | 'BACKFILL' | 'RECONSTRUCTION';

/**
 * Terminal states for a run. Fixed by ck_pipeline_run__outcome_known.
 *
 * 'RUNNING' is the state a row is INSERTED with. It cannot presently be
 * transitioned — see the append-only defect recorded in
 * docs/db-v2/16-phase8-s2-migration-findings.md (M-1). The type includes it
 * because the CHECK constraint does.
 */
export type RunOutcome = 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'PARTIAL';

/** A committed operations.pipeline_run row, addressed by its composite key. */
export interface PipelineRunRef {
  readonly id: string;
  readonly occurredAt: Date;
  readonly runKey: string;
  readonly triggerKind: TriggerKind;
  readonly startedAt: Date;
  /** Role that opened the run. Every job within it uses the same role's pool. */
  readonly role: PipelineRole;
}

interface RunContext {
  readonly ref: PipelineRunRef;
  /** Outcomes of the jobs recorded within this run, for the run's own summary. */
  readonly jobOutcomes: string[];
}

const runStorage = new AsyncLocalStorage<RunContext>();

/** The run active on this async execution path, if any. */
export function currentRun(): PipelineRunRef | null {
  return runStorage.getStore()?.ref ?? null;
}

/** Records a job outcome against the ambient run, for its closing summary. */
export function noteJobOutcome(outcome: string): void {
  runStorage.getStore()?.jobOutcomes.push(outcome);
}

/**
 * The code revision recorded on every run.
 *
 * operations.pipeline_run.code_revision is NOT NULL, deliberately: a run whose
 * code version is unknown cannot be reproduced, and reproducibility is the point
 * of recording runs at all. Deployments set PT_V2_CODE_REVISION to the commit
 * SHA. 'unknown' is accepted rather than fatal so a developer machine works, and
 * it is visibly wrong in the data when it reaches an environment that matters.
 */
export function codeRevision(): string {
  return process.env.PT_V2_CODE_REVISION?.trim() || 'unknown';
}

/**
 * The instant an operational row is stamped with.
 *
 * SUPPLIED BY THE APPLICATION, NOT BY now(), AND THAT IS LOAD-BEARING.
 *
 * occurred_at is half of every composite key in this schema — pipeline_job_run
 * pairs (pipeline_run_id, run_occurred_at); failure pairs
 * (pipeline_job_run_id, job_occurred_at); snapshot.match_snapshot pairs
 * (pipeline_job_run_id, pipeline_job_run_occurred_at) under P-04.
 *
 * PostgreSQL stores timestamptz at MICROSECOND precision. A JavaScript Date
 * carries MILLISECONDS. So a value generated by the column default, returned to
 * the application, and sent back as the second half of a foreign key ARRIVES
 * TRUNCATED and matches nothing:
 *
 *     stored   2026-08-03 09:24:31.363472+00
 *     returned 2026-08-03 09:24:31.363    (JS Date)
 *     sent     2026-08-03 09:24:31.363000+00   -> foreign key violation
 *
 * Found by the S-2 suite, where every job run failed to attach to its pipeline
 * run. Generating the instant here means it only ever has precision JavaScript
 * can represent, so the round trip is lossless and the composite key matches.
 *
 * EVERY FUTURE SUBSYSTEM PAIRING ON A timestamptz MUST DO THE SAME — S-7 in
 * particular, whose sealing writes carry the job run's instant into
 * snapshot.match_snapshot.
 */
export function operationalNow(): Date {
  return new Date();
}

/**
 * Inserts a pipeline_run and returns its composite reference.
 *
 * `control` must be a connection OUTSIDE any business transaction. The whole
 * point of the operational layer is that its rows survive a rollback of the work
 * they describe, and a row inserted inside that transaction does not.
 */
export async function insertPipelineRun(
  control: PoolClient,
  role: PipelineRole,
  runKey: string,
  triggerKind: TriggerKind,
  scopeText?: string
): Promise<PipelineRunRef> {
  const startedAt = new Date();
  const occurredAt = operationalNow();
  const { rows } = await control.query<{ id: string }>(
    `INSERT INTO operations.pipeline_run
       (occurred_at, run_key, trigger_kind, scope_text, started_at, outcome, code_revision)
     VALUES ($1, $2, $3, $4, $5, 'RUNNING', $6)
     RETURNING id::text`,
    [occurredAt, runKey, triggerKind, scopeText ?? null, startedAt, codeRevision()]
  );
  return {
    id: rows[0].id,
    occurredAt,
    runKey,
    triggerKind,
    startedAt,
    role,
  };
}

/**
 * Whether operations run rows can be closed by UPDATE.
 *
 * Probed once per process rather than assumed. Today the answer is no —
 * operations.pipeline_run carries the append-only guard, which raises on UPDATE
 * for every principal, and no role holds UPDATE on it. See finding M-1.
 *
 * This is a probe rather than a hard-coded `false` so that the moment the
 * architecture owner corrects the defect, the application starts closing runs
 * with no code change. Until then it attempts once, learns, and stops.
 */
let closeSupported: boolean | null = null;

/** Test-only. Forces the capability probe to run again. */
export function resetCloseCapabilityForTesting(): void {
  closeSupported = null;
}

/** Diagnostic: what the probe concluded, or null if it has not run. */
export function runCloseCapability(): boolean | null {
  return closeSupported;
}

/**
 * Attempts to record a terminal outcome on a run or job row.
 *
 * Returns true when the close landed, false when the schema does not permit it.
 * NEVER THROWS on the append-guard path: a telemetry limitation must not turn a
 * successful pipeline into a failed one, and must not replace the error of a
 * failing one.
 */
export async function tryCloseRow(
  control: PoolClient,
  relation: 'pipeline_run' | 'pipeline_job_run',
  id: string,
  occurredAt: Date,
  outcome: string
): Promise<boolean> {
  if (closeSupported === false) return false;
  try {
    await control.query(
      `UPDATE operations.${relation === 'pipeline_run' ? 'pipeline_run' : 'pipeline_job_run'}
          SET outcome = $3, ended_at = now()
        WHERE id = $1 AND occurred_at = $2`,
      [id, occurredAt, outcome]
    );
    if (closeSupported === null) {
      closeSupported = true;
      logger.info('v2: operations run rows are closable — outcomes will be recorded');
    }
    return true;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (closeSupported === null) {
      closeSupported = false;
      logger.warn(
        { err: message },
        'v2: operations run rows CANNOT be closed (append-only guard / no UPDATE grant). ' +
          'Runs will remain RUNNING and ended_at will stay NULL. This is migration finding ' +
          'M-1 — see docs/db-v2/16-phase8-s2-migration-findings.md. Terminal outcomes are ' +
          'still recorded for failures, in operations.failure.'
      );
    }
    return false;
  }
}

export interface PipelineRunOptions {
  /** Defaults to MANUAL, which is what a directly-invoked pipeline is. */
  readonly triggerKind?: TriggerKind;
  /** Free text describing what the run covered — a date, a competition. */
  readonly scopeText?: string;
  /**
   * Overrides the generated run key.
   *
   * uq_pipeline_run__run_key is UNIQUE (run_key, occurred_at). Supply an
   * explicit key only when the caller needs to find the row again by name.
   */
  readonly runKey?: string;
}

/**
 * Opens a pipeline run, executes `fn` within it, and closes it.
 *
 * Every withRun() inside `fn` — at any await depth — attaches its job to this
 * run. Concurrent calls to withPipelineRun in one process each get their own
 * ambient context and cannot see each other's.
 *
 * The run is opened and closed on a DEDICATED CONNECTION that never carries a
 * business transaction, so nothing `fn` does can roll the run away.
 */
export async function withPipelineRun<T>(
  role: PipelineRole,
  runKey: string,
  fn: () => Promise<T>,
  options: PipelineRunOptions = {}
): Promise<T> {
  // THE CONTROL CONNECTION IS NOT HELD FOR THE DURATION OF THE BODY.
  //
  // The first implementation held it from open to close. That cost three
  // connections per pipeline — the run's control, plus withRun's control and
  // work connections — and with the deliberately small pools of R-05 (four for
  // ingestion) two concurrent pipelines exhausted the pool and DEADLOCKED
  // AGAINST THEMSELVES: the held control connections could not be released until
  // bodies completed, and the bodies could not complete without connections.
  //
  // The suite found it as a hang, not as an error, which is the worst way to
  // find anything. Acquiring only for the insert and again for the close costs
  // two round trips of checkout and reduces steady-state pressure to withRun's
  // two connections, so a pool of four supports two concurrent pipelines rather
  // than deadlocking on one.
  const pool = poolFor(role);
  const opener = await pool.connect();
  let ref: PipelineRunRef;
  try {
    ref = await insertPipelineRun(
      opener,
      role,
      options.runKey ?? runKey,
      options.triggerKind ?? 'MANUAL',
      options.scopeText
    );
  } finally {
    opener.release();
  }

  const context: RunContext = { ref, jobOutcomes: [] };
  let outcome: RunOutcome;
  try {
    const result = await runStorage.run(context, fn);
    const failed = context.jobOutcomes.filter((o) => o === 'FAILED').length;
    outcome =
      failed === 0 ? 'SUCCEEDED' : failed === context.jobOutcomes.length ? 'FAILED' : 'PARTIAL';
    await closeRun(pool, ref, outcome);
    logger.info(
      { role, runKey: ref.runKey, runId: ref.id, jobs: context.jobOutcomes.length, outcome },
      'v2: pipeline run finished'
    );
    return result;
  } catch (err) {
    await closeRun(pool, ref, 'FAILED');
    logger.error(
      {
        role,
        runKey: ref.runKey,
        runId: ref.id,
        err: err instanceof Error ? err.message : String(err),
      },
      'v2: pipeline run failed'
    );
    throw err;
  }
}

/**
 * Closes a run on a briefly-acquired connection.
 *
 * Never throws: a telemetry limitation must not turn a successful pipeline into
 * a failed one, and must not replace the error of a failing one. Today the close
 * cannot land at all — finding M-1 — and this still returns cleanly.
 */
async function closeRun(pool: Pool, ref: PipelineRunRef, outcome: RunOutcome): Promise<void> {
  let closer: PoolClient | undefined;
  try {
    closer = await pool.connect();
    await tryCloseRow(closer, 'pipeline_run', ref.id, ref.occurredAt, outcome);
  } catch (err) {
    logger.warn(
      { runId: ref.id, err: err instanceof Error ? err.message : String(err) },
      'v2: could not acquire a connection to close the pipeline run'
    );
  } finally {
    closer?.release();
  }
}

/**
 * Ensures a run exists for the current execution path.
 *
 * Used by the job lifecycle when a stage is invoked outside withPipelineRun.
 * The caller owns releasing the control connection it returns, and must call the
 * returned `finish` exactly once.
 */
export async function ensureImplicitRun(
  control: PoolClient,
  role: PipelineRole,
  jobKey: string
): Promise<{ ref: PipelineRunRef; implicit: boolean }> {
  const existing = currentRun();
  if (existing) return { ref: existing, implicit: false };
  const ref = await insertPipelineRun(
    control,
    role,
    `implicit:${jobKey}`,
    'MANUAL',
    'Implicit run — stage invoked outside withPipelineRun()'
  );
  return { ref, implicit: true };
}
