// ─────────────────────────────────────────────────────────────────────────────
// PIPELINE RUNS — operations.pipeline_run
//
// A pipeline EXECUTION owns exactly one pipeline_run. Every attributed stage
// within it owns one pipeline_job_run (jobLifecycle.ts). The run is the outer
// bracket; the jobs are the stages inside it.
//
// WHY AsyncLocalStorage RATHER THAN A PARAMETER
// S-1's public contract is fixed: withRun(role, jobKey, fn, options). It may not
// be redesigned, and it takes no run argument. The run therefore has to reach
// the lifecycle some other way, and an ambient context is the only mechanism
// that does not change the signature every caller already uses.
//
// AsyncLocalStorage propagates across await boundaries correctly, which a module
// global would not: two pipelines running concurrently in one process each see
// their own run, and neither can observe the other's. The concurrency test in
// operations.test.ts asserts exactly that.
//
// WHY A RUN IS CREATED IMPLICITLY WHEN NONE IS ACTIVE
// A stage invoked directly — from the CLI, from a test — still needs a run,
// because pipeline_job_run.pipeline_run_id is NOT NULL and the composite foreign
// key to pipeline_run admits no exception. Rather than fail such a call, an
// implicit single-stage run is opened around it. The trigger kind is MANUAL,
// which is what it is.
// ─────────────────────────────────────────────────────────────────────────────

import { AsyncLocalStorage } from 'node:async_hooks';
import type { Pool, PoolClient } from 'pg';
import { poolFor } from '../db/pool';
import type { PipelineRole } from '../db/roles';
import { logger } from '../../utils/logger';

/**
 * How a run came to be started. Values are fixed by
 * ck_pipeline_run__trigger_known and are not extensible from the application.
 */
export type TriggerKind = 'SCHEDULED' | 'MANUAL' | 'BACKFILL' | 'RECONSTRUCTION';

/**
 * Terminal states for a run. Fixed by ck_pipeline_run__outcome_known.
 *
 * 'RUNNING' is the IMMUTABLE INITIAL STATE of the run row and is never written
 * to a completion record — a completion saying the run is still running is not a
 * completion. Terminal states are recorded by appending to
 * operations.pipeline_run_completion (migration 019, finding M-1).
 */
export type RunOutcome = 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'PARTIAL';

/** Terminal outcomes only — what may appear on a completion record. */
export type TerminalRunOutcome = Exclude<RunOutcome, 'RUNNING'>;

/** A committed operations.pipeline_run row, addressed by its composite key. */
export interface PipelineRunRef {
  readonly id: string;
  readonly occurredAt: Date;
  readonly runKey: string;
  readonly triggerKind: TriggerKind;
  readonly startedAt: Date;
  /** Role that opened the run. Every job within it uses the same role's pool. */
  readonly role: PipelineRole;
}

interface RunContext {
  readonly ref: PipelineRunRef;
  /** Outcomes of the jobs recorded within this run, for the run's own summary. */
  readonly jobOutcomes: string[];
}

const runStorage = new AsyncLocalStorage<RunContext>();

/** The run active on this async execution path, if any. */
export function currentRun(): PipelineRunRef | null {
  return runStorage.getStore()?.ref ?? null;
}

/** Records a job outcome against the ambient run, for its closing summary. */
export function noteJobOutcome(outcome: string): void {
  runStorage.getStore()?.jobOutcomes.push(outcome);
}

/**
 * The code revision recorded on every run.
 *
 * operations.pipeline_run.code_revision is NOT NULL, deliberately: a run whose
 * code version is unknown cannot be reproduced, and reproducibility is the point
 * of recording runs at all. Deployments set PT_V2_CODE_REVISION to the commit
 * SHA. 'unknown' is accepted rather than fatal so a developer machine works, and
 * it is visibly wrong in the data when it reaches an environment that matters.
 */
export function codeRevision(): string {
  return process.env.PT_V2_CODE_REVISION?.trim() || 'unknown';
}

/**
 * The instant an operational row is stamped with.
 *
 * SUPPLIED BY THE APPLICATION, NOT BY now(), AND THAT IS LOAD-BEARING.
 *
 * occurred_at is half of every composite key in this schema — pipeline_job_run
 * pairs (pipeline_run_id, run_occurred_at); failure pairs
 * (pipeline_job_run_id, job_occurred_at); snapshot.match_snapshot pairs
 * (pipeline_job_run_id, pipeline_job_run_occurred_at) under P-04.
 *
 * PostgreSQL stores timestamptz at MICROSECOND precision. A JavaScript Date
 * carries MILLISECONDS. So a value generated by the column default, returned to
 * the application, and sent back as the second half of a foreign key ARRIVES
 * TRUNCATED and matches nothing:
 *
 *     stored   2026-08-03 09:24:31.363472+00
 *     returned 2026-08-03 09:24:31.363    (JS Date)
 *     sent     2026-08-03 09:24:31.363000+00   -> foreign key violation
 *
 * Found by the S-2 suite, where every job run failed to attach to its pipeline
 * run. Generating the instant here means it only ever has precision JavaScript
 * can represent, so the round trip is lossless and the composite key matches.
 *
 * EVERY FUTURE SUBSYSTEM PAIRING ON A timestamptz MUST DO THE SAME — S-7 in
 * particular, whose sealing writes carry the job run's instant into
 * snapshot.match_snapshot.
 */
export function operationalNow(): Date {
  return new Date();
}

/**
 * Inserts a pipeline_run and returns its composite reference.
 *
 * `control` must be a connection OUTSIDE any business transaction. The whole
 * point of the operational layer is that its rows survive a rollback of the work
 * they describe, and a row inserted inside that transaction does not.
 */
export async function insertPipelineRun(
  control: PoolClient,
  role: PipelineRole,
  runKey: string,
  triggerKind: TriggerKind,
  scopeText?: string
): Promise<PipelineRunRef> {
  const startedAt = new Date();
  const occurredAt = operationalNow();
  const { rows } = await control.query<{ id: string }>(
    `INSERT INTO operations.pipeline_run
       (occurred_at, run_key, trigger_kind, scope_text, started_at, outcome, code_revision)
     VALUES ($1, $2, $3, $4, $5, 'RUNNING', $6)
     RETURNING id::text`,
    [occurredAt, runKey, triggerKind, scopeText ?? null, startedAt, codeRevision()]
  );
  return {
    id: rows[0].id,
    occurredAt,
    runKey,
    triggerKind,
    startedAt,
    role,
  };
}

/**
 * Appends a terminal completion record for a run or a job run.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THIS REPLACES tryCloseRow(), AND THE REASON IS ARCHITECTURAL
 *
 * The first S-2 implementation attempted `UPDATE … SET outcome, ended_at` and
 * discovered it could never succeed: operations.pipeline_run and
 * pipeline_job_run carry the append-only guard, which raises on UPDATE for every
 * principal without exception (R-19), and no role holds UPDATE on either. Runs
 * stayed RUNNING for ever. That was finding M-1.
 *
 * Inserting the row once at completion instead is foreclosed by P-04: the job
 * run must be committed DURING the work so snapshot.match_snapshot can reference
 * it compositely.
 *
 * Migration 019 resolves it with the pattern A.2 already established for
 * snapshot outcome revision — an append-only companion carrying ordinal
 * succession. Nothing is updated, no guard is weakened, and no UPDATE privilege
 * exists anywhere. A correction to a recorded outcome is a new row at a higher
 * ordinal, and the earlier record stays readable.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * NEVER THROWS. A telemetry failure must not turn a successful pipeline into a
 * failed one, nor replace the error of a failing one. Returns false when the
 * completion could not be appended, having logged why.
 */
export async function appendCompletion(
  control: PoolClient,
  target: CompletionTarget,
  id: string,
  occurredAt: Date,
  outcome: string,
  endedAt: Date = operationalNow()
): Promise<boolean> {
  const spec = COMPLETION_SPEC[target];
  try {
    // The ordinal is allocated from the existing succession for this run. A
    // first completion is ordinal 1; a later correction is 2, and so on.
    //
    // The partition predicate on occurred_at is mandatory on a partitioned
    // relation (§5.10.6) and F-15 registers a conformance check that detects
    // reads without one. A completion is always within days of the run it
    // completes, so a bounded lookback is both correct and prunable.
    await control.query(
      `INSERT INTO operations.${spec.relation}
         (occurred_at, ${spec.idColumn}, ${spec.instantColumn}, ended_at, outcome, ordinal)
       SELECT $1, $2, $3, $4, $5,
              COALESCE((SELECT max(c.ordinal) + 1
                          FROM operations.${spec.relation} c
                         WHERE c.occurred_at >= $3::timestamptz - interval '30 days'
                           AND c.${spec.idColumn} = $2
                           AND c.${spec.instantColumn} = $3), 1)`,
      [operationalNow(), id, occurredAt, endedAt, outcome]
    );
    return true;
  } catch (err) {
    logger.error(
      {
        relation: spec.relation,
        id,
        outcome,
        err: err instanceof Error ? err.message : String(err),
      },
      'v2: could not append completion record'
    );
    return false;
  }
}

/** Which completion relation a target uses, and how it addresses its parent. */
type CompletionTarget = 'pipeline_run' | 'pipeline_job_run';

const COMPLETION_SPEC: Readonly<
  Record<CompletionTarget, { relation: string; idColumn: string; instantColumn: string }>
> = {
  pipeline_run: {
    relation: 'pipeline_run_completion',
    idColumn: 'pipeline_run_id',
    instantColumn: 'run_occurred_at',
  },
  pipeline_job_run: {
    relation: 'pipeline_job_run_completion',
    idColumn: 'pipeline_job_run_id',
    instantColumn: 'job_occurred_at',
  },
};

/**
 * The prevailing completion for a run, or null while it is still in flight.
 *
 * Highest ordinal wins, with occurred_at and id breaking a tie deterministically
 * — the partition key participates in the uniqueness constraint, so a duplicate
 * ordinal is possible in principle, and an arbitrary winner is the defect class
 * Phase 7 recorded as DB-04.
 */
export async function currentCompletion(
  control: PoolClient,
  target: CompletionTarget,
  id: string,
  occurredAt: Date
): Promise<{ outcome: string; endedAt: Date; ordinal: number } | null> {
  const spec = COMPLETION_SPEC[target];
  const { rows } = await control.query<{ outcome: string; ended_at: Date; ordinal: number }>(
    `SELECT outcome, ended_at, ordinal
       FROM operations.${spec.relation}
      WHERE occurred_at >= $2::timestamptz - interval '30 days'
        AND ${spec.idColumn} = $1
        AND ${spec.instantColumn} = $2
      ORDER BY ordinal DESC, occurred_at DESC, id DESC
      LIMIT 1`,
    [id, occurredAt]
  );
  if (rows.length === 0) return null;
  return { outcome: rows[0].outcome, endedAt: rows[0].ended_at, ordinal: rows[0].ordinal };
}

export interface PipelineRunOptions {
  /** Defaults to MANUAL, which is what a directly-invoked pipeline is. */
  readonly triggerKind?: TriggerKind;
  /** Free text describing what the run covered — a date, a competition. */
  readonly scopeText?: string;
  /**
   * Overrides the generated run key.
   *
   * uq_pipeline_run__run_key is UNIQUE (run_key, occurred_at). Supply an
   * explicit key only when the caller needs to find the row again by name.
   */
  readonly runKey?: string;
}

/**
 * Opens a pipeline run, executes `fn` within it, and closes it.
 *
 * Every withRun() inside `fn` — at any await depth — attaches its job to this
 * run. Concurrent calls to withPipelineRun in one process each get their own
 * ambient context and cannot see each other's.
 *
 * The run is opened and closed on a DEDICATED CONNECTION that never carries a
 * business transaction, so nothing `fn` does can roll the run away.
 */
export async function withPipelineRun<T>(
  role: PipelineRole,
  runKey: string,
  fn: () => Promise<T>,
  options: PipelineRunOptions = {}
): Promise<T> {
  // THE CONTROL CONNECTION IS NOT HELD FOR THE DURATION OF THE BODY.
  //
  // The first implementation held it from open to close. That cost three
  // connections per pipeline — the run's control, plus withRun's control and
  // work connections — and with the deliberately small pools of R-05 (four for
  // ingestion) two concurrent pipelines exhausted the pool and DEADLOCKED
  // AGAINST THEMSELVES: the held control connections could not be released until
  // bodies completed, and the bodies could not complete without connections.
  //
  // The suite found it as a hang, not as an error, which is the worst way to
  // find anything. Acquiring only for the insert and again for the close costs
  // two round trips of checkout and reduces steady-state pressure to withRun's
  // two connections, so a pool of four supports two concurrent pipelines rather
  // than deadlocking on one.
  const pool = poolFor(role);
  const opener = await pool.connect();
  let ref: PipelineRunRef;
  try {
    ref = await insertPipelineRun(
      opener,
      role,
      options.runKey ?? runKey,
      options.triggerKind ?? 'MANUAL',
      options.scopeText
    );
  } finally {
    opener.release();
  }

  const context: RunContext = { ref, jobOutcomes: [] };
  let outcome: RunOutcome;
  try {
    const result = await runStorage.run(context, fn);
    const failed = context.jobOutcomes.filter((o) => o === 'FAILED').length;
    outcome =
      failed === 0 ? 'SUCCEEDED' : failed === context.jobOutcomes.length ? 'FAILED' : 'PARTIAL';
    await closeRun(pool, ref, outcome);
    logger.info(
      { role, runKey: ref.runKey, runId: ref.id, jobs: context.jobOutcomes.length, outcome },
      'v2: pipeline run finished'
    );
    return result;
  } catch (err) {
    await closeRun(pool, ref, 'FAILED');
    logger.error(
      {
        role,
        runKey: ref.runKey,
        runId: ref.id,
        err: err instanceof Error ? err.message : String(err),
      },
      'v2: pipeline run failed'
    );
    throw err;
  }
}

/**
 * Records a run's terminal state on a briefly-acquired connection.
 *
 * Never throws: telemetry must not decide the fate of the work it describes.
 */
async function closeRun(pool: Pool, ref: PipelineRunRef, outcome: RunOutcome): Promise<void> {
  let closer: PoolClient | undefined;
  try {
    closer = await pool.connect();
    await appendCompletion(closer, 'pipeline_run', ref.id, ref.occurredAt, outcome);
  } catch (err) {
    logger.warn(
      { runId: ref.id, err: err instanceof Error ? err.message : String(err) },
      'v2: could not acquire a connection to complete the pipeline run'
    );
  } finally {
    closer?.release();
  }
}

/**
 * Ensures a run exists for the current execution path.
 *
 * Used by the job lifecycle when a stage is invoked outside withPipelineRun.
 * The caller owns releasing the control connection it returns, and must call the
 * returned `finish` exactly once.
 */
export async function ensureImplicitRun(
  control: PoolClient,
  role: PipelineRole,
  jobKey: string
): Promise<{ ref: PipelineRunRef; implicit: boolean }> {
  const existing = currentRun();
  if (existing) return { ref: existing, implicit: false };
  const ref = await insertPipelineRun(
    control,
    role,
    `implicit:${jobKey}`,
    'MANUAL',
    'Implicit run — stage invoked outside withPipelineRun()'
  );
  return { ref, implicit: true };
}
